# Generated by Django 2.2.6 on 2019-10-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oders',
            name='Order_Product',
        ),
        migrations.AddField(
            model_name='product',
            name='Order_Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_for_product', to='startapp.Oders'),
            preserve_default=False,
        ),
    ]
