# Generated by Django 2.2.6 on 2019-10-13 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0004_auto_20191013_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='Confirm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='oders',
            name='Remove',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='oders',
            name='Order_Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_for_product', to='startapp.Product'),
        ),
    ]
