# Generated by Django 2.2.6 on 2019-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0005_auto_20191013_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Gif',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
