# Generated by Django 2.2.6 on 2019-10-17 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0006_product_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oders',
            name='Order_Client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_for_client', to=settings.AUTH_USER_MODEL),
        ),
    ]
