# Generated by Django 2.2.6 on 2019-10-17 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0008_auto_20191018_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oders',
            name='Order_Product',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, related_name='order_for_product', to='startapp.Product'),
            preserve_default=False,
        ),
    ]
