# Generated by Django 2.2.6 on 2019-10-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startapp', '0010_auto_20191018_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='oders',
            name='See',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
